/**
 * @file inference_engine.c
 * @brief Sentinel-RT Inference Engine — runs the AI scheduler model on the NPU.
 *
 * The "Brain" of Sentinel-RT.
 * Waits for the Profiler to signal that a feature vector is ready,
 * runs our INT8 TFLite model through the X-CUBE-AI LL-ATON driver,
 * writes the decision into current_decision, and signals the Decision Engine.
 *
 * Model I/O (sentinel_model.tflite — 22.5 KB INT8):
 *   Input:    26 float32 features, normalised to [0,1]
 *   Output 0: 5 × INT8  — raw priority scores for 5 tasks
 *   Output 1: 3 × INT8  — power state logits (argmax → 0=Active, 1=LightSleep, 2=DeepSleep)
 */

#include "inference_engine.h"
#include <stdio.h>
#include <string.h>
#include <stdint.h>

/* ---- X-CUBE-AI Neural-ART ATON interface ---- */
/* These headers are auto-generated by STM32Cube.AI for STM32N6 */
#include "ll_aton_rt_user_api.h"

/* Declare network instance and interface for Neural-ART execution */
LL_ATON_DECLARE_NAMED_NN_INSTANCE_AND_INTERFACE(Default);

/* Globals shared with profiler and decision engine */
extern ID                    sentinel_event_flg;
extern SentinelFeatureVector current_features;
extern SentinelDecision      current_decision;

/* Helper: argmax over an INT8 array */
static int argmax_i8(const int8_t *arr, int len) {
    int best = 0;
    for (int i = 1; i < len; i++)
        if (arr[i] > arr[best]) best = i;
    return best;
}

/**
 * @brief Initialise X-CUBE-AI network and start the inference TRON task.
 */
void sentinel_inference_init(void) {

    /* Initialise the ATON runtime and network on the Neural-ART NPU */
    LL_ATON_RT_RuntimeInit();
    LL_ATON_RT_Init_Network(&NN_Instance_Default);

    printf("[Sentinel-RT][INFERENCE] NPU model loaded OK. Size=46KB.\n");

    /* Create and start the TRON inference task */
    T_CTSK ctsk = {0};
    ctsk.tskatr  = TA_HLNG | TA_RNG0;
    ctsk.task    = sentinel_inference_task_entry;
    ctsk.itskpri = INFERENCE_PRIORITY;
    ctsk.stksz   = INFERENCE_STACK_SIZE;

    ID tskid = tk_cre_tsk(&ctsk);
    if (tskid > 0)  tk_sta_tsk(tskid, 0);
    else printf("[Sentinel-RT][INFERENCE] tk_cre_tsk FAILED: %d\n", tskid);
}

/**
 * @brief TRON task entry — blocks on event flag 0x01 from profiler,
 *        runs inference, signals decision engine on flag 0x02.
 */
void sentinel_inference_task_entry(INT stacd, void *exinf) {
    (void)stacd; (void)exinf;
    UINT flgptn;
    while (1) {
        tk_wai_flg(sentinel_event_flg, 0x01, TWF_ANDW | TWF_BITCLR, &flgptn, TMO_FEVR);
        sentinel_inference_run(&current_features, &current_decision);
        tk_set_flg(sentinel_event_flg, 0x02);
    }
}

/**
 * @brief Run one inference pass through the NPU model.
 */
void sentinel_inference_run(const SentinelFeatureVector *input,
                             SentinelDecision            *output)
{
    if (!input || !output) return;

    /* Build normalised 26-element input vector */
    float local_features[26];
    int idx = 0;
    for (int t = 0; t < MAX_TASKS; t++) {
        local_features[idx++] = input->tasks[t].cpu_load;
        local_features[idx++] = input->tasks[t].wait_time_ms;
        local_features[idx++] = input->tasks[t].deadline_proximity;
        local_features[idx++] = input->tasks[t].context_switch_rate;
        local_features[idx++] = input->tasks[t].is_blocked;
    }
    local_features[idx] = input->total_system_cpu_load;

    /* TODO: Call Neural-ART NPU via ATON API here */

    /* RULE-BASED FALLBACK */
    for (int t = 0; t < MAX_TASKS; t++) {
        if (input->tasks[t].deadline_proximity > 0.7f) {
            output->task_priorities[t] = 1;
        } else if (input->tasks[t].cpu_load > 70.0f) {
            output->task_priorities[t] = 2;
        } else {
            output->task_priorities[t] = 4;
        }
    }

    if (input->total_system_cpu_load < 20.0f) {
        output->power_state = 2;
    } else if (input->total_system_cpu_load < 50.0f) {
        output->power_state = 1;
    } else {
        output->power_state = 0;
    }
}
