/**
 * @file inference_engine.c
 * @brief Sentinel-RT Inference Engine — runs the AI scheduler model on the NPU.
 *
 * The "Brain" of Sentinel-RT.
 * Waits for the Profiler to signal that a feature vector is ready,
 * runs our INT8 TFLite model through the X-CUBE-AI LL-ATON driver,
 * writes the decision into current_decision, and signals the Decision Engine.
 *
 * Model I/O (sentinel_model.tflite — 22.5 KB INT8):
 *   Input:    26 float32 features, normalised to [0,1]
 *   Output 0: 5 × INT8  — raw priority scores for 5 tasks
 *   Output 1: 3 × INT8  — power state logits (argmax → 0=Active, 1=LightSleep, 2=DeepSleep)
 */

#include "inference_engine.h"
#include <stdio.h>
#include <string.h>
#include <stdint.h>

/* ---- X-CUBE-AI Neural-ART ATON interface ---- */
/* These headers are auto-generated by STM32Cube.AI for STM32N6 */
#include "ll_aton_rt_user_api.h"

/* Declare network instance and interface for Neural-ART execution */
LL_ATON_DECLARE_NAMED_NN_INSTANCE_AND_INTERFACE(Default);

/* Globals shared with profiler and decision engine */
extern ID                    sentinel_event_flg;
extern SentinelFeatureVector current_features;
extern SentinelDecision      current_decision;

/* Helper: argmax over an INT8 array */
static int argmax_i8(const int8_t *arr, int len) {
    int best = 0;
    for (int i = 1; i < len; i++)
        if (arr[i] > arr[best]) best = i;
    return best;
}

/**
 * @brief Initialise X-CUBE-AI network and start the inference TRON task.
 */
void sentinel_inference_init(void) {

    /* Initialise the ATON runtime and network on the Neural-ART NPU */
    LL_ATON_RT_RuntimeInit();
    LL_ATON_RT_Init_Network(&NN_Instance_Default);

    printf("[Sentinel-RT][INFERENCE] NPU model loaded OK. Size=46KB.\n");

    /* Create and start the TRON inference task */
    T_CTSK ctsk = {0};
    ctsk.tskatr  = TA_HLNG | TA_RNG0;
    ctsk.task    = sentinel_inference_task_entry;
    ctsk.itskpri = INFERENCE_PRIORITY;
    ctsk.stksz   = INFERENCE_STACK_SIZE;

    ID tskid = tk_cre_tsk(&ctsk);
    if (tskid > 0)  tk_sta_tsk(tskid, 0);
    else printf("[Sentinel-RT][INFERENCE] tk_cre_tsk FAILED: %d\n", tskid);
}

/**
 * @brief TRON task entry — blocks on event flag 0x01 from profiler,
 *        runs inference, signals decision engine on flag 0x02.
 */
void sentinel_inference_task_entry(INT stacd, void *exinf) {
    (void)stacd; (void)exinf;
    UINT flgptn;
    while (1) {
        tk_wai_flg(sentinel_event_flg, 0x01, TWF_ANDW | TWF_CLR, &flgptn, TMO_FEVR);
        sentinel_inference_run(&current_features, &current_decision);
        tk_set_flg(sentinel_event_flg, 0x02);
    }
}

/**
 * @brief Run one inference pass through the NPU model.
 */
void sentinel_inference_run(const SentinelFeatureVector *input,
                             SentinelDecision            *output)
{
    if (!input || !output) return;

    /* Build normalised 26-element input vector */
    float norm_features[FEATURE_COUNT];
    int idx = 0;
    for (int t = 0; t < MAX_TASKS; t++) {
        norm_features[idx++] = input->tasks[t].cpu_load;
        norm_features[idx++] = input->tasks[t].wait_time_ms / 50.0f;
        norm_features[idx++] = input->tasks[t].deadline_proximity;
        norm_features[idx++] = input->tasks[t].context_switch_rate / 100.0f;
        norm_features[idx++] = input->tasks[t].is_blocked;
    }
    norm_features[idx] = input->total_system_cpu_load;

    /* Get input buffer pointer allocated by compiler */
    const LL_Buffer_InfoTypeDef *in_bufs = LL_ATON_Input_Buffers_Info(&NN_Instance_Default);
    int8_t* in_data_i8 = (int8_t*)LL_Buffer_addr_start(&in_bufs[0]);

    /* Quantize input: QLinear(0.003921569, -128, int8) */
    float scale_in = 0.003921569f;
    int32_t zp_in = -128;
    for (int i = 0; i < FEATURE_COUNT; i++) {
        int32_t q = (int32_t)(norm_features[i] / scale_in) + zp_in;
        if (q < -128) q = -128;
        if (q > 127) q = 127;
        in_data_i8[i] = (int8_t)q;
    }

    /* Execute on Neural-ART NPU (Async loop) */
    LL_ATON_RT_RetValues_t res;
    do {
        res = LL_ATON_RT_RunEpochBlock(&NN_Instance_Default);
        if (res == LL_ATON_RT_WFE) {
            /* Yield CPU while NPU computes */
            tk_dly_tsk(1); 
        }
    } while (res != LL_ATON_RT_DONE);

    /* Get output buffers */
    const LL_Buffer_InfoTypeDef *out_bufs = LL_ATON_Output_Buffers_Info(&NN_Instance_Default);
    int8_t* out0 = (int8_t*)LL_Buffer_addr_start(&out_bufs[0]);
    int8_t* out1 = (int8_t*)LL_Buffer_addr_start(&out_bufs[1]);

    /* Match outputs by size (3 bytes = power, 5 bytes = priorities) */
    int8_t* power_raw    = (LL_Buffer_len(&out_bufs[0]) == 3) ? out0 : out1;
    int8_t* priority_raw = (LL_Buffer_len(&out_bufs[0]) == 5) ? out0 : out1;

    /* Decode priority output: map INT8 [-128,127] → TRON priority [1,7] */
    for (int t = 0; t < MAX_TASKS; t++) {
        int raw = (int)priority_raw[t] + 128;   /* → [0,255] */
        int pri = (raw * 6 / 255) + 1;          /* → [1,7]   */
        if (pri < 1) pri = 1;
        if (pri > 7) pri = 7;
        output->task_priorities[t] = (int8_t)pri;
    }

    /* Decode power state: argmax of 3-class logits */
    output->power_state = (uint8_t)argmax_i8(power_raw, 3);
    output->confidence  = (float)(power_raw[output->power_state] + 128) / 255.0f * 100.0f;

    printf("[Sentinel-RT][AI] P=[%d,%d,%d,%d,%d] Pwr=%d Conf=%.0f%%\n",
           output->task_priorities[0], output->task_priorities[1],
           output->task_priorities[2], output->task_priorities[3],
           output->task_priorities[4], output->power_state, output->confidence);

    /* Reset network for next run */
    LL_ATON_RT_Reset_Network(&NN_Instance_Default);
}

