/**
 * @file inference_engine.c
 * @brief Implementation of the NN Inference Engine component (Brain)
 */
#include "inference_engine.h"
#include <stdio.h>

extern ID sentinel_event_flg;
extern SentinelFeatureVector current_features;
extern SentinelDecision current_decision;

/**
 * @brief Initializes the inference engine and loads the model on NPU
 */
void sentinel_inference_init(void) {
    T_CTSK ctsk = {0};
    ctsk.tskatr = TA_HLNG | TA_RNG0;
    ctsk.task = sentinel_inference_task_entry;
    ctsk.itskpri = INFERENCE_PRIORITY;
    ctsk.stksz = INFERENCE_STACK_SIZE;

    ID tskid = tk_cre_tsk(&ctsk);
    if (tskid > 0) {
        tk_sta_tsk(tskid, 0);
    }
}

/**
 * @brief uT-Kernel task entry function
 */
void sentinel_inference_task_entry(INT stacd, void *exinf) {
    (void)stacd;
    (void)exinf;
    UINT flgptn;

    while (1) {
        /* Wait on event flag from profiler */
        tk_wai_flg(sentinel_event_flg, 0x01, TWF_ANDW | TWF_CLR, &flgptn, TMO_FEVR);

        /* Run inference */
        sentinel_inference_run(&current_features, &current_decision);

        /* Signal decision engine */
        tk_set_flg(sentinel_event_flg, 0x02);
    }
}

/**
 * @brief Runs inference
 */
void sentinel_inference_run(const SentinelFeatureVector *input, SentinelDecision *output) {
    if (!input || !output) return;

    /* TODO: STM32Cube.AI integration */
    /* Actual NPU code will be generated by STM32Cube.AI and linked here. */
    /* For example: ai_network_run(...) */
}
